<template>
	<ul class="words">
		<li>A</li>
		<li>B</li>
		<li>C</li>
		<li>D</li>
		<li>E</li>
		<li>F</li>
		<li>G</li>
		<li>H</li>
		<li>I</li>
		<li>J</li>
		<li>K</li>
		<li>L</li>
		<li>M</li>
		<li>N</li>
		<li>O</li>
		<li>P</li>
		<li>Q</li>
		<li>R</li>
		<li>S</li>
		<li>T</li>
		<li>U</li>
		<li>V</li>
		<li>W</li>
		<li>X</li>
		<li>Y</li>
		<li>Z</li>
	</ul>
</template>
<script>
	export default{
		name:"Words",
		data(){
			return{

			}
		}
	}
</script>
<style lang="stylus" scoped>
	.words
		width:0.8rem
		position:absolute
		top:7.6rem
		right:0
		bottom:0
		z-index:99
		font-size:0.32rem
		color:#00bcd4
		display:flex
		flex-direction:column
		justify-content:center
		align-items:center
</style>